version: '3'

run: once

# allow setting CUSTOM_WS_PROFILE_DIR via .env file
dotenv: ['.env']

vars:
  PIP_OPTS: "--no-input --no-cache-dir --prefer-binary --upgrade"

tasks:
  default:
    cmds:
      - cmd: task --list
        ignore_error: true
        silent: true

  deps:pre-commit:
    desc: Install pre-commit
    internal: true
    sources:
      - requirements.txt
    cmds:
      - pip install {{.PIP_OPTS}} pre-commit
      - pre-commit install
    status:
      - pre-commit --version
      - test -f .git/hooks/pre-commit

  profiles:push:
    desc: Pushes profiles to the default profiles directory
    aliases:
      - push
    cmds:
      - python .scripts/sync_profiles.py push {{if .CUSTOM_WS_PROFILE_DIR}}'{{.CUSTOM_WS_PROFILE_DIR}}'{{end}}

  profiles:pull:
    desc: Pulls profiles from the default profiles directory
    aliases:
      - pull
    cmds:
      - python .scripts/sync_profiles.py pull {{if .CUSTOM_WS_PROFILE_DIR}}'{{.CUSTOM_WS_PROFILE_DIR}}'{{end}}
      - task: profiles:clean

  profiles:clean:
    desc: Cleans up profile config files (comments, blanks, etc.)
    aliases:
      - clean
    sources:
      # only run if a profile has changed
      - profiles/**/*
    cmds:
      - python .scripts/clean_conf_files.py

  profiles:build:
    desc: Generates an importable profile bundle (after cleaning)
    aliases:
      - build
    deps:
      - clean
    sources:
      # only run if a profile has changed
      - profiles/**/*
    generates:
      # or if no output files already exist
      - .output/wireshark-profiles_bcbrookman_*.*.*.zip
    cmds:
      - python .scripts/build_profiles.py

  test:pre-commit:
    desc: Run pre-commit tests
    aliases:
      - test
    deps:
      - deps:pre-commit
    cmds:
      - pre-commit run --all-files
